name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS | BB - ${{ github.event.inputs.base-branch }} | TB - ${{ github.event.inputs.target-branch }} | WD - ${{ github.event.inputs.working-directory }}
on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: The branch used as the base for the dependency update checks
        default: main
      target-branch:
        description: The branch from which the PR is created
        default: update-dependencies
      working-directory:
        description: The working directory of the project to check for dependency updates
        default: 17-custom-actions/react-app
jobs:
  dependency-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for dendency updates
        uses: ./.github/actions/js-dependency-update
        with:
          base-branch: ${{ github.event.inputs.base-branch }}
          target-branch: ${{ github.event.inputs.target-branch }}
          working-directory: ${{ github.event.inputs.working-directory }}
